export const UPDATE_START_QUERY = 'App/UPDATE_START_STRING';
export const INIT_START_SUGGESTIONS_FETCH = 'APP/INIT_START_SUGGESTIONS_FETCH';
export const UPDATE_START_SUGGESTIONS = 'APP/UPDATE_START_SUGGESTIONS';

export const UPDATE_END_QUERY = 'App/UPDATE_END_STRING';
export const INIT_END_SUGGESTIONS_FETCH = 'APP/INIT_END_SUGGESTIONS_FETCH';
export const UPDATE_END_SUGGESTIONS = 'APP/UPDATE_END_SUGGESTIONS';
