export const UPDATE_START_QUERY = 'App/UPDATE_START_STRING';
export const UPDATE_START_SUGGESTIONS = 'APP/UPDATE_START_SUGGESTIONS';

export const UPDATE_END_QUERY = 'App/UPDATE_END_STRING';
export const UPDATE_END_SUGGESTIONS = 'APP/UPDATE_END_SUGGESTIONS';

export const SELECT_START_POINT = 'App/SELECT_START_POINT';
export const SELECT_END_POINT = 'App/SELECT_END_POINT';
